name: action-demo

on:
  push:
    paths:
      - .github/workflows/action-demo.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 24f2008463@ds.study.iitm.ac.in
        run: echo "Hello, world! This workflow runs only once."
